### ISSUE TITLE
package.json - dependencies

### ISSUE THREAD

**Issue by ghost** [js-data/js-data-adapter#12]
It really requires dependencies:
  - chai
  - mocha
  - sinon

Would not it be better as devDependencies?

**Comment by beldougie** [comment]
The inclusion of mocha as a dependency rather than devDependency is causing a vulnerability alert on install - I can't believe these are needed at runtime. Happy to provide a PR to fix if you like?

**Comment by crobinson42** [comment]
Yeah that would be great, thanks!

**Comment by einat-bar** [comment]
@crobinson42 I have opened a PR for this:
https://github.com/js-data/js-data-adapter/pull/14
can someone please approve & merge it any time soon?

**Comment by beldougie** [comment]
Not only will this solve the errors being reported by npm audit, but it should reduce the size of deployed apps a little too - please someone review and merge this soon 😃

**Comment by einat-bar** [comment]
@jmdobry , can you please assist us and merge this PR?
https://github.com/js-data/js-data-adapter/pull/14
 thanks

**Comment by crobinson42** [comment]
@einat-bar It was merged a few hours ago.

**Comment by crobinson42** [comment]
Waiting for npmjs publish access on this package and will publish v1.0.1 and update this thread. In the meantime if there's any urgency you can reference the git repo url in your package.json file.

**Comment by einat-bar** [comment]
@crobinson42 Thanks! 
In my case, the security warnings are actually coming from js-data-http which is using js-data-adapter,
since js-data-adapter is using sinon in dependencies.

**Comment by einat-bar** [comment]
@crobinson42 I see now that in  js-data-http, you moved js-data-adapter to devDep, is there a reason for that?

**Comment by einat-bar** [comment]
@crobinson42 @jmdobry Is it possible to publish soon?

**Comment by crobinson42** [comment]
v1.0.1 published
