### ISSUE TITLE
Implicit any in d.ts

### ISSUE THREAD

**Issue by zakjan** [js-data/js-data-adapter#3]
The d.ts file throws errors when compiled with TS noImplicitAny strict option. For example `def, IDict` is probably a typo, it should be `def: IDict`?

**Comment by jmdobry** [comment]
Yep, typo.

**Comment by jmdobry** [comment]
Fixed in 0.6.2

**Comment by zakjan** [comment]
@jmdobry Also `...any` -> `...array: any[]`. Sorry I forgot to report it in the first post.
